### ISSUE TITLE
Build themes with Whiskers

### ISSUE THREAD

**Issue by uncenter** [catppuccin/aseprite#13]
I'd like to add Catppuccin's in-house build tool, https://github.com/catppuccin/whiskers, to build the themes for Aseprite. I can generate most of the files necessary but I don't know how the sheet.pngs were created - is there a base SVG we can apply Whiskers against and then convert the resulting SVGs to PNGs?

**Comment by sofycat** [comment]
from what I know there is a base png although no svg from what I know off

**Comment by sofycat** [comment]
although the cattpuccin theme is already drawn differently to the base sheet.png

**Comment by uncenter** [comment]
> although the cattpuccin theme is already drawn differently to the base sheet.png

Can you elaborate? Do we still need it?

**Comment by sofycat** [comment]
sorry im a bit dumb ;w;

what exactly are you trying to do? :3 
all themes are already created

**Comment by uncenter** [comment]
If the palette updates, how will you update the themes?

**Comment by sofycat** [comment]
ill do it myself :p

**Comment by uncenter** [comment]
Definitely could be a thing, though the issue is we don't have a base SVG (text-based image format) to give to Whiskers to process. We could use Whiskers to generate the XML though, if that is desired. Either way I'll leave this up to @sofycat, no need to adopt Whiskers if they don't want to!

**Comment by uncenter** [comment]
> * GH Action uses whiskers to generate all flavours and accents then converts to final png with imagemagick (or similar tool) `magick -background none sheet-export.svg sheet.png` + the accompanying metadata

Typically we use a build script locally rather than a CI action to reduce complexity, though we could try that.

**Comment by sofycat** [comment]
> Also looking at the sprite sheet it's missing quite a few sprites so an update is needed.

ill like into that rn!
Sorry for the confusion everyone i just generally don't know what whiskers is ;w;

**Comment by sofycat** [comment]
after looking into whiskers i honestly think its easier for me to just maintain this by hand :)

**Comment by sofycat** [comment]
@Covkie if you can do whatever needs to be done for me that would be great ^-^
I recently pushed an updated sheet.png for all themes :3
